version: '3.5'

services:
  mongodb:
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongodb
      - MONGO_INITDB_ROOT_PASSWORD=mongodb
      - MONGO_INITDB_DATABASE=cringelazer
    ports:
      - "127.0.0.1:27017:27017"
    volumes:
      - ./db:/data/db
      - ./logs/mongo:/var/log/mongodb
